### ISSUE TITLE
[DEV] Support authenticated requests to SMD

### ISSUE THREAD

**Issue by synackd** [OpenCHAMI/bss#22]
**Short Description**
BSS requests Components, ComponentEndpoints, and RedfishEndpoints from SMD, and these endpoints are now protected. Therefore, BSS must support authentication with these endpoints.

**Definition of Done**
Querying BSS endpoints that require communication to SMD succeed when running SMD and BSS with authentication enabled.

**Comment by davidallendj** [comment]
Related PR #23

**Comment by synackd** [comment]
#23 adds this functionality. Still to do are:

- [ ] Have a dynamic callback URL or remove it altogether for client credentials grants.
- [ ] Make scope dynamic.

@davidallendj Anything I'm missing?

**Comment by davidallendj** [comment]
Sounds right to me.
