### ISSUE TITLE
[BUG] BSS container race condition with docker compose

### ISSUE THREAD

**Issue by njones-lanl** [OpenCHAMI/bss#31]
**Describe the bug**
BSS seems to not have a good ready state for docker compose while using JWT authentication with hydra.  It seems to mark ready when the bss binary is running, not when it's gotten its first token and is ready to serve requests.

**To Reproduce**
Run the quickstart compose.

**Expected behavior**
I'd expect a different readyness endpoint maybe for when the service is ready to serve requests vs when it's running?

**Comment by alexlovelltroy** [comment]
The code change seems to help, but it also appears to trigger a build error.  https://github.com/OpenCHAMI/bss/actions/runs/8983805918

I _think_ it doesn't like the capitalization on the import. OpenCHAMI/jwtauth/v5 might need to be converted to openchami/jwtauth/v5

**Comment by davidallendj** [comment]
That's odd since SMD has the same import.
https://github.com/OpenCHAMI/smd/blob/main/cmd/smd/routers.go#L31
It looks like the builds for SMD were failing for a different reason as well.
https://github.com/OpenCHAMI/smd/actions/runs/8383461156

**Comment by alexlovelltroy** [comment]
Yeah. I wasn't sure of the reason. SMD appears to build and upload, but can't seem to attest. It looks like bss fails to build.

**Comment by davidallendj** [comment]
I opened a PR to update the `go.sum` and `go.mod` files which may fix the issue with PR #33.

**Comment by synackd** [comment]
I have not observed this during my testing on multiple clusters since the merge of the #33 above. I'm going to close this issue as resolved. If this is still an issue, we can revisit it.
