### ISSUE TITLE
[DEV] Update the github actions to gate merges to main on succesful compilation, linting, and successful unit tests

### ISSUE THREAD

**Issue by alexlovelltroy** [OpenCHAMI/bss#4]
**Short Description**
The current GitHub Actions come from the HPE team and are not applicable to our setup.  We need to set up our own hygiene.

**Definition of Done**
A successful completion of this task will update the repository configuration and github actions such that they enforce our code quality standards and review requirements.

**Comment by synackd** [comment]
We definitely also need to modify the integration tests (and perhaps the GitHub Actions for them) so that the actual tests run. Since none of them currently run right now, all of the tests currently fail in CI.

**Comment by alexlovelltroy** [comment]
We can close this based on the current gating unit tests from https://github.com/OpenCHAMI/bss/commit/dc387615f95f30782584333bf8dc0fdc3de0dc3f
