### ISSUE TITLE
[Quality] Update BSS database handling code to use migrations and favor environment variables for config

### ISSUE THREAD

**Issue by alexlovelltroy** [OpenCHAMI/bss#5]
While creating a deployment recipe, I had to trace the postgres connection information.  I couldn't figure out how to pass in a database name or how to add a migration for database schema(s).  I found that neither of these things are possible and left this note in an issue for further cleanup. 

We'll need to add a lot more detail to this issue before we can schedule it for work.

**Comment by synackd** [comment]
@alexlovelltroy With the merging of #6 and #13, should this be considered done or do we still need to address:

> how to add a migration for database schema(s)

?
