### ISSUE TITLE
[BUG] BSS POST not returns 201 but data missing in database if `hosts` are not valid xnames

### ISSUE THREAD

**Issue by Masber** [OpenCHAMI/bss#51]
**Describe the bug**
Dear OCHAMI development team,
I am testing OCHANI through deployment-recipes repo, I can deploy OCHAMI but for some reason I am unable to store data in BSS.

**To Reproduce**

1. Start OCHAMI following the deployment-recipes quickstart instructions
2. Run command 
```
curl --cacert cacert.pem -H "Authorization: Bearer $ACCESS_TOKEN" https://foobar.openchami.cluster:8443/boot/v1/bootparameters -v -d '{"hosts": [test1.local", "test2.local"], "macs": ["00:40:a6:82:f6:c5","a4:bf:01:3e:c0:a2","00:40:a6:82:f7:0c"], "nids": [1, 2, 3], "params": "test", "kernel": "test", "initrd": "test", "cloud-init": {"user-data": {"foo": "bar"},"meta-data": {"foo": "bar"}}}'
...
< HTTP/2 201
< bss-referral-token: bd6f0308-bb1d-4335-b802-3550b7aec5ea
< content-type: application/json; charset=UTF-8
< date: Wed, 27 Nov 2024 19:13:06 GMT
< content-length: 0
<
* Connection #0 to host foobar.openchami.cluster left intact
```
4. Run command
```
curl --cacert cacert.pem -H "Authorization: Bearer $ACCESS_TOKEN" https://foobar.openchami.cluster:8443/boot/v1/bootparameters -v
...
< HTTP/2 200
< content-type: application/json; charset=UTF-8
< date: Wed, 27 Nov 2024 19:15:08 GMT
< content-length: 5
<
null
* Connection #0 to host foobar.openchami.cluster left intact
```

**Expected behavior**
http post is not storing data in postgres
However, adding correct xnames works

```
curl --cacert cacert.pem -H "Authorization: Bearer $ACCESS_TOKEN" https://foobar.openchami.cluster:8443/boot/v1/bootparameters -v \
-d '{"hosts": ["x0c0s2b0n0", "x0c0s3b0n0"], "macs": ["00:40:a6:82:f6:c5","a4:bf:01:3e:c0:a2","00:40:a6:82:f7:0c"], "nids": [1, 2, 3], "params": "test", "kernel": "test", "initrd": "test", "cloud-init": {"user-data": {"foo": "bar"},"meta-data": {"foo": "bar"}}}'
```

**Screenshots**
NA

**Desktop (please complete the following information):**
```
cat /etc/*release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=24.10
DISTRIB_CODENAME=oracular
DISTRIB_DESCRIPTION="Ubuntu 24.10"
PRETTY_NAME="Ubuntu 24.10"
NAME="Ubuntu"
VERSION_ID="24.10"
VERSION="24.10 (Oracular Oriole)"
VERSION_CODENAME=oracular
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=oracular
LOGO=ubuntu-logo
```

**Smartphone (please complete the following information):**
NA

**Additional context**
NA

**Comment by alexlovelltroy** [comment]
I didn't think BSS supported identifiers other than xnames.  Is that feature supported on a CSM system with BSS?

**Comment by Masber** [comment]
I assume it would only work with valid xnames.
However, BSS validates the mac addresses so I would assume it should also validate xnames and return a 401 error if the xnames are not valid? I think returning 201 is misleading since it tells the client the request was successful processed (new entry created) but it is not.
Also, would OCHAMI support hostnames different than xnames? myabe this last question should added to the roadmap to discuss?

**Comment by Masber** [comment]
Example of a request with wrong mac addresses

```
curl --cacert cacert.pem -H "Authorization: Bearer $ACCESS_TOKEN" https://foobar.openchami.cluster:8443/boot/v1/bootparameters -d '{"hosts": ["x0c0s2b0n0", "x0c0s3b0n0"], "macs": ["00","a4","00"], "nids": [1, 2, 3], "params": "test", "kernel": "test", "initrd": "test", "cloud-init": {"user-data": {"foo": "bar"},"meta-data": {"foo": "bar"}}}'
{"type":"about:blank","title":"Bad Request","detail":"Bad Request: invalid MAC address format: 00\n","status":400}
```

I would assume a similar error message if xnames are not valid

**Comment by alexlovelltroy** [comment]
We're having a separate discussion about supporting hostnames in https://github.com/OpenCHAMI/smd/issues/43. The architecture from the HPE code uses xname as the primary key for many operations in BSS as well as SMD.

Having said that, I don't think it's unreasonable to update BSS such that it validates the xnames when creating bootparameters.  I will propose a fix in a branch.
