### ISSUE TITLE
[DEV] Update the Dockerfile with comments that describe what environment variables are read by the service and how they are used.

### ISSUE THREAD

**Issue by alexlovelltroy** [OpenCHAMI/bss#8]
Closing #6 will change the way things like helm charts and docker-compose files need to prepare for bss.  We need to give folks some breadcrumbs to follow.

**Comment by alexlovelltroy** [comment]
@synackd can we close this? I don't see a bunch of unlabled environment variables in the Dockerfile anymore.

**Comment by synackd** [comment]
I still see a few, and it might be worth documenting the available environment variables and what they do. I can make a PR that adds that.

**Comment by synackd** [comment]
This is complete with the merge of #18.
